version: '3.8'

services:
  rifaapp-backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: rifaapp-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USE_LOCAL_DB=true
    volumes:
      - ./backend/data.json:/app/data.json:z
    restart: always
